version: "3.9"

services:

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5005:5000"
    # เพิ่มการระบุ sqlite เพื่อความถาวรของข้อมูล metadata
    command: mlflow server --backend-store-uri sqlite:////mlflow/mlflow.db --default-artifact-root /mlflow/mlruns --host 0.0.0.0
    volumes:
      - ./mlruns:/mlflow/mlruns
      - ./mlflow.db:/mlflow/mlflow.db # เชื่อม DB ไว้ที่นี่

  studentcare-api:
    build: .
    container_name: studentcare-api
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./mlruns:/app/mlruns
      - ./mlflow.db:/app/mlflow.db
    command: uvicorn src.api.app:app --host 0.0.0.0 --port 8000 --reload

  studentcare-frontend:
    build: .
    container_name: studentcare-frontend
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./mlruns:/app/mlruns
      - ./mlflow.db:/app/mlflow.db
    command: streamlit run src/frontend/app.py --server.port 8501 --server.address 0.0.0.0