version: '3.8'

services:
  # 1. ตัว Backend (FastAPI)
  api:
    build: .
    image: educare_api_image:latest
    container_name: educare_api_v2
    command: uvicorn src.api.app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  # 2. ตัว Frontend (Streamlit)
  frontend:
    build: .
    image: educare_frontend_image:latest
    container_name: educare_frontend_v2
    command: streamlit run src/frontend/app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - api